services:
  postgres:
    container_name: projeto_cadastro_login_postgres
    image: postgres:15
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${USER_POSTGRES}
      - POSTGRES_PASSWORD=${PASSWORD_POSTGRES}
      - POSTGRES_DB=projeto_cadastro_login
