services:
  postgres:
    container_name: projeto_cadastro_login_postgres
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      - SPRING_DATASOURCE_USERNAME=${USER_POSTGRES}
      - SPRING_DATASOURCE_PASSWORD=${PASSWORD_POSTGRES}
      - SPRING_APPLICATION_NAME=projeto_cadastro_login